sonar.organization=kshishtovsky
sonar.projectKey=kshishtovsky_fluint
sonar.projectName=fluint
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,docs/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
